export const CHANGE_BACKGROUND = 'CHANGE_BACKGROUND';

export const CLEAR_AUTH_INFO = 'CLEAR_AUTH';
export const FULL_LOGIN = 'FULL_LOGIN';
export const UPDATE_LOGIN = 'UPDATE_LOGIN';
export const UPDATE_USER_ID = 'UPDATE_USER_ID';
export const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN';